timeout: 3600s

substitutions:
  _CLUSTER: devnet-pragma
  _NAMESPACE: indexer
  _DOMAIN: indexer.devnet.pragma.build
  _ENVIRONMENT: Production

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: docker-build
    env:
      - 'DOCKER_BUILDKIT=1'
    args: [ 'build',
            '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}',
            '--file=Dockerfile',
            '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: docker-push
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/curl'
    id: install-infisical
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -1sLf \
          'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' \
          | bash
        apt-get update && apt-get install -y infisical
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: get-credentials
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER}'
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: install-helm
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: helm-deploy
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Login to Infisical
        infisical login --token="$$INFISICAL_TOKEN"

        # Export secrets to .env file
        infisical export --env=${_ENVIRONMENT} --format=dotenv > .env

        # Deploy with Helm
        helm upgrade --install pragma-indexer ./helm \
          --namespace ${_NAMESPACE} \
          --create-namespace \
          --set image.tag=${SHORT_SHA} \
          --set image.repository=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME} \
          --set ingress.host=${_DOMAIN} \
          --wait --timeout 10m
    secretEnv: ['INFISICAL_TOKEN']
    waitFor: ['docker-push', 'install-helm', 'get-credentials', 'install-infisical']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/infisical-token/versions/2
      env: 'INFISICAL_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
