version: "3"

services:
  indexing:
    build: .
    env_file:
      - .env
    environment:
      - APIBARA_ETCD_URL=http://host.docker.internal:2379
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432
      - APIBARA_POSTGRES_CONNECTION_STRING=postgres://postgres:postgres@host.docker.internal:5432/postgres
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - 8080:8080
    networks:
      - ls

  localstack:
    image: localstack/localstack:2.0
    hostname: localstack
    ports:
      - "4566:4566" # LocalStack endpoint
      - "4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=sqs,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./scripts/setup-localstack.sh:/etc/localstack/init/ready.d/script.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ls

networks:
  ls:
    name: ls
