version: "3"

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - ls

  localstack:
    image: localstack/localstack:2.0
    hostname: localstack
    ports:
      - "4566:4566" # LocalStack endpoint
      - "4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./scripts/setup-localstack.sh:/etc/localstack/init/ready.d/script.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ls
      
  onchain-db:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    networks:
      - ls
    volumes:
      - onchain-db-data:/var/lib/postgresql/data
      - type: bind
        source: ${PWD}/infra/onchain-db/01-init.sql
        target: /docker-entrypoint-initdb.d/01-init.sql
    environment:
      - POSTGRES_DB=pragma
      - PGPORT=5432
      - POSTGRES_PASSWORD=pragma_password
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ls:
    name: ls

volumes:
  onchain-db-data: