version: "3"

services:

  indexing:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - ls

  localstack:
    image: localstack/localstack:2.0
    hostname: localstack
    ports:
      - '4566:4566' # LocalStack endpoint
      - '4510-4559:4510-4559' # external services port range
    environment:
      - SERVICES=sqs,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./scripts/setup-localstack.sh:/etc/localstack/init/ready.d/script.sh
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - ls

networks:
  ls:
    name: ls
