path: "/"
container_port: 8080
alb_scheme: internal
health_check_path: "/health"
container_environment:
  - region: "eu-west-3"
  - prefix: "/conf/{{ SERVICE_NAME }}/{{ RUN_ENV }}"
  - keys:
      - DATABASE_URL
      - HOST
      - PORT
      - APIBARA_AUTH_TOKEN
      - APIBARA_DNA_STREAM_URL
      - APIBARA_ETCD_URL
      - APIBARA_POSTGRES_CONNECTION_STRING
      - BINARY_BASE_PATH
      - INDEXER_SERVICE_BUCKET