---
name: Task - Rust Tests & Coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  coverage:
    # sadly, for now we have to "rebuild" for the coverage
    runs-on: ubuntu-latest

    env:
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
      AWS_REGION: eu-west-3
      LOCALSTACK_ENDPOINT: http://localhost:4566
      BINARY_BASE_PATH: /bin
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      APIBARA_AUTH_TOKEN: ${{ secrets.APIBARA_AUTH_TOKEN }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Download sink binaries
        run: |
          wget https://github.com/apibara/dna/releases/download/sink-webhook/v0.3.0/sink-webhook-x86_64-linux.gz
          gunzip sink-webhook-x86_64-linux.gz
          sudo cp sink-webhook-x86_64-linux /bin/sink-webhook

#      - name: Start LocalStack
#        run: |
#          pip install localstack awscli-local
#          docker pull localstack/localstack
#          localstack start -d
#
#          echo "Waiting for LocalStack startup..."
#          localstack wait -t 30
#          echo "Startup complete"
#
#      - name: Create S3 Bucket and SQS Queues
#        run: |
#          awslocal s3api create-bucket --bucket indexer-service --region eu-west-3 --create-bucket-configuration LocationConstraint=eu-west-3
#          awslocal s3api put-object --bucket indexer-service --key apibara-scripts/
#          awslocal s3api list-buckets
#          awslocal sqs create-queue --queue-name indexer-service-start-indexer
#          awslocal sqs create-queue --queue-name indexer-service-failed-indexer
#          awslocal sqs create-queue --queue-name indexer-service-stop-indexer
#          awslocal sqs list-queues

      - name: Clean workspace
        run: |
          cargo llvm-cov clean --workspace

      - name: Run llvm-cov
        run: |
          cargo test -- --test-threads=1 --nocapture

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: false
