---
name: Task - Rust Tests & Coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  coverage:
    # sadly, for now we have to "rebuild" for the coverage
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: Swatinem/rust-cache@v2
      
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Clean workspace
        run: |
          cargo llvm-cov clean --workspace

      - name: Run llvm-cov
        run: |
          cargo llvm-cov nextest --release --test-threads=1 --no-report

      - name: Generate report
        run: |
          cargo llvm-cov report --lcov --codecov --output-path codecov.json

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: codecov.json
          fail_ci_if_error: false
