---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml
    needs: changelog

  rust_build:
    name: Build Rust project
    uses: ./.github/workflows/rust-build.yml
    needs: changelog

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: rust_build
