---
name: Task - Build Rust

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: ['aws', 'gcp']
    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.feature }}

      - name: Build the project
        run: |
          cargo build --release --workspace --no-default-features --features ${{ matrix.feature }}

